command_timeout = 1000
scan_timeout = 10

[directory]
truncation_length = 50
truncate_to_repo = false

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[username]
style_user = 'bold red'
format = '\[USER: [$user]($style)\] '
disabled = false
show_always = true
